apiVersion: v1
kind: Service
metadata:
  labels:
    app: DealService
  name: DealService
spec:
  type: NodePort
  ports:
  - port: 8588
    protocol: TCP
    targetPort: 8588
    nodePort: 
  selector:
    app: DealService